package com.asiainfo.httpsws.eaopbase;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.1.3-hudson-390-
 * Generated source version: 2.0
 */
@WebService(name = "EaopServer", targetNamespace = "http://eaop.gd.chinamobile.com/")
public interface EaopServer {
	/**
	 * @param arg0
	 * @return
	 *         returns java.lang.String
	 */
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "handle", targetNamespace = "http://eaop.gd.chinamobile.com/", className = "com.dzqd.eaop.ws.client.Handle")
	@ResponseWrapper(localName = "handleResponse", targetNamespace = "http://eaop.gd.chinamobile.com/", className = "com.dzqd.eaop.ws.client.HandleResponse")
	public String handle(@WebParam(name = "arg0", targetNamespace = "") String arg0);
	
	@WebMethod
	@WebResult(targetNamespace = "")
	@RequestWrapper(localName = "handle", targetNamespace = "http://eaop.gd.chinamobile.com/", className = "com.dzqd.eaop.ws.client.Handle")
	@ResponseWrapper(localName = "handleResponse", targetNamespace = "http://eaop.gd.chinamobile.com/", className = "com.dzqd.eaop.ws.client.HandleResponse")
	public String handle2(@WebParam(name = "arg0", targetNamespace = "") String arg0,@WebParam(name = "sign", targetNamespace = "") String sign);
}
